version: '3.3'
services:
  postgres:
    image: postgres
    env_file: ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - .:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - bridge
  server:
    container_name: backend
    build:
      context: ./backend
    ports:
      - '3001:3001'
    environment:
      NODE_ENV: production
    env_file: ./.env
    depends_on:
      - postgres
    command: npm start:prod
    volumes:
      - ~/app/media/.:/app/media/.
    networks:
      - bridge
  client:
    build: ./client
    container_name: client_frontend
    ports:
      - '3000:3000'
    networks:
      - bridge
  nginx:
    image: nginx:bookworm
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/pashaev-fund.ru/fullchain.pem:ro
      - /etc/letsencrypt/live/pashaev-fund.ru/privkey.pem:ro
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    networks:
      - bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  bridge:
    driver: bridge
